### PR TITLE
Add Winget installation instructions

### PR DESCRIPTION
**Pull request by sitiom**
OpenFreebuds can now be installed via [Winget](https://learn.microsoft.com/en-us/windows/package-manager/):
```
winget install MelianMiko.OpenFreebuds
```

Note: If you want to update the [Winget package](https://github.com/microsoft/winget-pkgs/tree/master/manifests/m/MelianMiko/OpenFreebuds), install [Komac](https://github.com/russellbanks/Komac) and run the `komac update` command. For example:
```bash
komac update -i MelianMiko.OpenFreebuds -v 0.13.1 -u https://st.mmk.pw/openfreebuds/openfreebuds_0.13.1_win32.exe
```
- https://github.com/microsoft/winget-pkgs/pull/138240

You can automate this via [Winget Releaser](https://github.com/vedantmgoyal2009/winget-releaser), but it only works when the binaries are hosted in the [releases](https://github.com/melianmiko/OpenFreebuds/releases) page (You can use Komac directly instead, though).

### CODE REVIEW

**Comment by melianmiko** [comment]
Sorry, but I don't want to support winget, so don't want to recommend it as primary installation method. I'll add them as alternative install way, but for me primary installation option still will be downloading from website.

**Comment by sitiom** [comment]
Although you support AUR and Debian?

**Comment by melianmiko** [comment]
> Would be nice to have a "package manager" way to install for all platforms.

Now you have this way, but I don't want mark it as primary. At lease due to unavailability of `winget` in older Windows 10 releases, and my own disagree with Microsoft's politics.

<details>
<summary>offtop</summary>
Iin my Win 10-11 virtual machines for example winget doesn't work at all. In win10 (23h2 w/ all updates) it isn't available, in 11 it just returns to shell after few seconds, without any messages or errors. Maybe that's because I don't have MS account, idk.
</details>

**Comment by sitiom** [comment]
> At lease due to unavailability of `winget` in older Windows 10 releases

Yeah, at the minimum winget-cli requires at least Windows 10 1809, which is old enough anyway (EOL).

> In win10 (22h2 w/ all updates) it isn't available, in 11 it just returns to shell after few seconds, without any messages or errors. Maybe that's because I don't have MS account, idk.

You don't need an MS account to have Winget. You can update the [App Installer](https://apps.microsoft.com/detail/9NBLGGH4NNS1) package in the MS Store or install it directly from the [releases](https://github.com/microsoft/winget-cli/releases).

**Pull request closed without merging**
